### ISSUE TITLE
Deploy vuejs on githubpages

### ISSUE THREAD

**Issue by fredmadrid** [Genobank/genobank-app-shc-validator#8]
@MoMannn @xpepermint  we need your help deploying the app so @duribebe can demo.... with github pages work? if not can you help deploy to a host solution?

**Comment by MoMannn** [comment]
Its already on github pages... Its shc.genobank.io if you want to redeploy
just run: npm run deploy

V čet., 21. okt. 2021 22:05 je oseba fredmadrid ***@***.***>
napisala:

**Comment by fredmadrid** [comment]
@MoMannn thank you tadej!
